### ISSUE TITLE
Confusing code in the Reduce method Complex example

### ISSUE THREAD

**Issue by loopdeluce** [learn-co-curriculum/phase-1-using-array-reduce#8]
### Canvas Link

https://learning.flatironschool.com/courses/5192/assignments/185980?module_item_id=413184

### Concern

I think the const showcase should be const allShowcases! (in the visual studio complex reduce method example)

### Suggested Changes

I think the const showcase should be const allShowcases! (in the visual studio complex reduce method example)

**Comment by lizbur10** [comment]
Hi @loopdeluce! Thanks for bringing this to our attention! Hmm, yes, it looks like this lesson needs a little help. I'm going to leave this issue open for now and we will address it when we can do a more substantial rewrite.

Thanks for contributing to the Flatiron School curriculum 💙

**Comment by lizbur10** [comment]
Hi again @loopdeluce ! I have fixed the inconsistency in the variable name and also tried to expand the explanation of the example a bit more. Hopefully it's a bit clearer now 😃 

Thanks for contributing to the Flatiron School curriculum 💙
